set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_PREFIX /usr/x86_64-w64-mingw32)

set(CMAKE_C_COMPILER   x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_RC_COMPILER  x86_64-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH ${MINGW_PREFIX})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# SDL2 hints
set(SDL2_DIR ${MINGW_PREFIX}/lib/cmake/SDL2)
set(SDL2_INCLUDE_DIRS ${MINGW_PREFIX}/include/SDL2)
set(SDL2_LIBRARIES
    ${MINGW_PREFIX}/lib/libSDL2main.a
    ${MINGW_PREFIX}/lib/libSDL2.dll.a
)

# OpenGL (use opengl32 from MinGW)
set(OPENGL_FOUND TRUE)
set(OPENGL_INCLUDE_DIR ${MINGW_PREFIX}/include)
set(OPENGL_LIBRARIES opengl32)

